fix: Fix `std::exception`s not throwing, and provide more `HostObject<T>` info (#83)
4 things:

1. Fixes `std::exceptions` not being caught by our `catch` block
2. Fixes errors not rejecting the Promise, but instead resolving it with
an Error object
3. Adds more useful information when an invalid type is passed to a
`HostObject<T>`, such as the typename:
    ```
Error: Cannot convert "{ nativeFunc: [Function function] }" to
HostObject<margelo::FilamentBuffer>! It is a different HostObject<T>!
    ```
4. When passing `undefined`/`nullptr`, use `jsi::Value::undefined`
instead of empty HostObjects/Objects.